shop/cart/urls.py
from django.urls import path
from . import views

app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('delete/<int:product_id>/',views.delete,name='delete'),
]

shop/searchapp/urls.py
from django.urls import path
from . import views

app_name = 'searchapp'

urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shopping_app.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/shopping_app/urls.py
from django.urls import path
from . import views
app_name = 'shopping_app'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>',views.prodDetail,name='prodCatDetail')
]

shop/cart/models.py
from django.db import models
from shopping_app.models import Products

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'
    
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
         return '{}'.format(self.product)

shop/searchapp/models.py
from django.db import models

# Create your models here.

shop/shopping_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Categories(models.Model):
    name = models.CharField(max_length=300,unique=True)
    slug = models.SlugField(max_length=300,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category_gallery',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return  reverse('shopping_app:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Products(models.Model):
    name = models.CharField(max_length=300,unique=True)
    slug = models.SlugField(max_length=300,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Categories,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_gallery',blank=True)
    stock = models.IntegerField()
    availability = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shopping_app:prodCatDetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

shop/cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shopping_app.models import Products
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Products.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart= cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for item in cart_items:
            total += (item.product.price * item.quantity)
            counter += item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
    
def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Products,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def delete(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Products,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

shop/searchapp/views.py
from django.shortcuts import render
from shopping_app.models import Products
from django.db.models import Q

# Create your views here.
def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Products.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

shop/shopping_app/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from . models import Categories,Products
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
def index(request):
    return HttpResponse("hello")

def allProdCat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Categories,slug=c_slug)
        products_list = Products.objects.all().filter(category=c_page,availability=True)
    else:
        products_list = Products.objects.all().filter(availability=True)
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':products})

def prodDetail(request,c_slug,p_slug):
    try:
        product = Products.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

shop/shopping_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
   
        {% include 'header.html' %}
        {% include 'nav.html' %}
        {% block content %}
        {% endblock%}
{% include 'footer.html' %}
<script src="{% static 'js\bootstrap.min.js' %}"></script>
<script src="{% static 'js\popper.min.js' %}"></script>
<script src="https://kit.fontawesome.com/1b99dd44bf.js" crossorigin="anonymous"></script>r
</body>
</html>

shop/shopping_app/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription%}
    Review items in your Kart and place order
{% endblock %}
{% block title %}
    Kart - shopping cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div class="container-fluid">
    <div class="text-center">
        <h3 class="display-4">Your Kart is Empty</h3>
        <p class="lead"> Add some items from <a href="{% url 'shopping_app:allProdCat' %}">Here</a></p>
    </div>
</div>
{% else %}
<div class="container">
    <div class="text-center">
        <h3 class="display-5"> Selected Products :</h3>
    </div>
</div>
<div class="container text-center">
    <div class="mx-auto container-fluid text-center">
        <div class="col-12 col-lg-6 text-center">
            <table class="table">
                <thead class="cart_thead">
                    <tr>
                        <th colspan="5">
                            Your Items
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                    <tr>
                        <td>
                            <a href="item.product.get_absolute_url"><img src="{{item.product.image.url}}" alt="{{item.product.name}}" style="width: 200px; height: 200px;" class="float-left rounded-border"></a>
                        </td>
                        <td class="text-left" style="width: 40%;">
                            {{item.product.name}}
                            <br>
                            SKU: {{item.product.id}}
                            <br>
                            Price: ₹ {{item.product.price}}
                            <br>
                            Quantity: {{item.quantity}} x ₹ {{item.product.price}}
                        </td>
                        <td>
                            ₹ {{item.sub_total}}
                        </td>
                        {% if item.quantity < item.product.stock %}
                        <td>
                            <a href="{% url 'cart:add_cart' item.product.id %}" class="cart_link"> <i class="fa-solid fa-square-plus">&nbsp;</i> </a>
                            &nbsp;<a href="{% url 'cart:cart_remove' item.product.id %}" class="cart_link"><i class="fa-solid fa-square-minus cart_icon"></i></a>
                            &nbsp;<a href="{% url 'cart:delete' item.product.id %}" class="cart_link"><i class="fa-solid fa-trash cart_icon"></i></a>
                        </td>
                        {% else %}
                        <td>
                            &nbsp;<a href="{% url 'cart:cart_remove' item.product.id %}" class="cart_link"><i class="fa-solid fa-square-minus cart_icon"></i></a>
                            &nbsp;<a href="{% url 'cart:delete' item.product.id %}" class="cart_link"><i class="fa-solid fa-trash cart_icon"></i></a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-12 col-lg-6 text-center">
        <table class="table">
            <thead class="cart_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please check your cart items before placing your order.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Total Amount: <strong>{{total}}</strong>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shopping_app:allProdCat' %}" class="btn btn-info btn-block cart_button">Proceed</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

shop/shopping_app/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription%}
    {% if category %}
        {{category.description|truncatewords:150}}
    {% else %}
        Welcome to kart shopping store, buy everything you need for affordable cost
    {% endif %}
{% endblock %}

{% block title %}
    {%if category %}
        {{category.name}} from kart for unbelievable offers
    {% else %}
        Check out our new Collections
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="text-center explore">
                <p>
                    <a href="{% url 'shopping_app:allProdCat' %}" style="text-decoration: none;  color: #00f8f8;"> Explore More <i class="fa-solid fa-magnifying-glass-arrow-right fa-bounce"></i></a>
                </p>
            </div>
        </div>
    {% endif %}
    {% if category %}
        <div class="text-center"> 
            <img src="{{category.image.url}}" alt="{{category.name}}" width="500px" height="500px">
        </div>
        <br>
        <div class="text-center">
            <h1 class="display-4" style="font-size: 20px;">{{category.name}}</h1>
        </div>
        <div>
            <p class="lead text-center">{{category.description}}</p>
        </div>
    {% else %}
        <div class="container-fluid">
            <img src="{% static 'img/banner.png' %}" alt="banner" width="100%">
        </div>
        <br>
        <div>
            <h1 class="display-4 text-center">Shoppers asylum for the weekend</h1>
            <p class="lead text-center">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis amet quos eligendi eaque quasi quod deserunt aperiam molestias necessitatibus iure possimus nostrum, voluptates consectetur quas iusto cupiditate optio facilis magnam.</p>
        </div>
    {% endif %}
    <div>
        <div class="container">
            <div class="row mx_auto">
                {% for product in products.object_list %}
                    <div class="col-9 col-sm-12 col-md-4 col-lg-4 gy-5">
                        <div class="card text-center" style="min-width:18rem">
                            <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" width="500px" height="500px"></a>
                                <div class="card-body" style="background-color: black; color: #00f8f8;">
                                    <h4 class="display-6" style="font-size: 20px; text-transform: uppercase; letter-spacing: .2em;">{{product.name}}</h4>
                                <p class="lead">₹{{product.price}}</p>
                                </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="mx-auto">
                {% if products.paginator.num_pages > 1 %}
                    <hr> 
                    <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}"> {{pg}} </a>
                    {% endfor %}
                    </div>
                {% endif %}
            </div>
            <br>
        </div>
    </div>
{% endblock %}

shop/shopping_app/templates/footer.html
<div class="footer navbar-fixed-bottom text-center my_footer">
    <p>
        @copyrighted by iso 9001 pvt ltd ISI IBM
    </p>
</div>

shop/shopping_app/templates/header.html
{% load static %}
<header>
    <div class="container-fluid header_space">
        <center>
            <img src="{% static 'img/logo.png' %}" alt="logo" width="200px" height="120px">
        </center>    
    </div>
</header>

shop/shopping_app/templates/nav.html
<ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'shopping_app:allProdCat' %}">All Categories</a>
    </li>
    {% for cat in links %}
    <li class="nav-item">
      <a class="nav-link" href="{{cat.get_url}}">{{cat.name}}</a>
    </li>
    {% endfor %}
    {% if item_count > 0%}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'cart:cart_detail' %}"> Your Kart <i class="fa-solid fa-cart-plus fa-shake"></i>[{{item_count}}]</a>
    </li>
    {% endif %}
    <li>
      <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </li>
</ul>

shop/shopping_app/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription%}
    {{category.description|truncatewords:150}}
{% endblock %}

{% block title %}
    {{category.name}} from kart for unbelievable offers
{% endblock %}

{% block content %}
    <div class="row">
        <div class="mx_auto">
            <p class="text-center"> <a href="{% url 'shopping_app:allProdCat' %}" style="text-decoration: none;  color: #00f8f8;">Home</a> | <a href="{{product.category.get_url}} " style="text-decoration: none;  color: #00f8f8;">{{product.name}}</a></p>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width: 18rem;">
                    <img src="{{product.image.url}}" alt="{{product.name}}">
                </div>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                <div>
                    <h1 class="display-4 product_name">{{product.name}}</h1>
                    <p>{{product.price}}</p>
                    <h4 class="product_name" style="color: white;"> Product Description</h4>
                    <p class="text-justify lead" style="color:white">{{product.description}}</p>
                    {% if product.stock == 0 %}
                        <p><b>Out of Stock</b></p>
                    {% else %}
                    <a class="btn btn-outline-light" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

shop/shopping_app/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription%}
    Unique Collections
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
    <div class="text-center"> <span class="display-4">Searching for:</span>
        <small class="display-6 text-white" >{{query}}</small>
    </div>
    <div class="container">
        <div class="row mx_auto">
            {% for product in products %}
                <div class="col-9 col-sm-12 col-md-4 col-lg-4 gy-5">
                    <div class="card text-center" style="min-width:18rem">
                        <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" width="500px" height="500px"></a>
                            <div class="card-body" style="background-color: black; color: #00f8f8;">
                                <h4 class="display-6" style="font-size: 20px; text-transform: uppercase; letter-spacing: .2em;">{{product.name}}</h4>
                            <p class="lead">₹{{product.price}}</p>
                            </div>
                    </div>
                </div>
            {% empty %}
            <div class="row mx-auto">
                <p class="text-center display-6 text-white" > No results found </p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}